Django4/thriftproject/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/',views.SignUpView.as_view(),name='signup'),
    path('signup_success/',views.SignUpSuccessView.as_view(),name='signup_success'),
    path('login/',auth_views.LoginView.as_view(template_name='login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='logout.html'),name='logout'),
]

Django4/thriftproject/thrift/urls.py
from django.urls import path
from . import views

app_name = 'thrift'

urlpatterns = [
    path('', views.IndexView.as_view(),name='index'),
    path('product-ditail/<int:pk>/',views.ProductDetail.as_view(),name='product_detail'),
    path('thrifts/<int:category>',views.CategoryView.as_view(),name = 'thrifts_cat'),
    path('mypage/',views.user_orders, name='mypage')
]

Django4/thriftproject/thriftproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('thrift.urls')),
    path('', include('accounts.urls')),
    path('paswword_reset/',auth_views.PasswordResetView.as_view(template_name="password_reset.html"),name='password_reset'),
    path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(template_name="password_reset_sent.html"),name="password_reset_done"),
    path('reset/<uidb64>/<token>',auth_views.PasswordResetConfirmView.as_view(template_name="password_reset_form.html"),name="password_reset_confirm"),
    path('reset/done/',auth_views.PasswordResetCompleteView.as_view(template_name="password_reset_done.html"),name='password_reset_complete'),
]

urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

Django4/thriftproject/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class CustomUser(AbstractUser):
    pass

Django4/thriftproject/thrift/models.py
from django.db import models
from accounts.models import CustomUser

# Create your models here.
class Category(models.Model):
    title = models.CharField(
        verbose_name='カテゴリ',
        max_length=20)
    
    def __str__(self):
        return self.title

class Gender(models.Model):
    gender = models.CharField(
        verbose_name='性別',
        max_length=6
    )

    def __str__(self):
        return self.gender
    
class ThriftRegister(models.Model):
    category = models.ForeignKey(
        Category,
        verbose_name='カテゴリ',
        on_delete=models.PROTECT,
        related_name='category'
    )

    title = models.CharField(
        verbose_name='商品名',
        max_length=100
    )

    gender = models.ForeignKey(
        Gender,
        verbose_name='性別',
        on_delete=models.PROTECT,
        related_name='genders'
    )

    size = models.CharField(
        verbose_name='サイズ',
        max_length=2
    )

    status = models.TextField(
        verbose_name='状態'
    )

    price = models.IntegerField(
        verbose_name='価格'
    )

    comment = models.TextField(
        verbose_name='コメント'
    )

    image1 = models.ImageField(
        verbose_name='イメージ１',
        upload_to="thrifts"
    )

    image2 = models.ImageField(
        verbose_name='イメージ２',
        upload_to='thrifts',
        blank=True,
        null=True
    )
    
    posted_at = models.DateTimeField(
        verbose_name='登録日',
        auto_now_add=True
    )

    is_purchased = models.BooleanField(
        default=False
        )

    def __str__(self):
        return self.title
    
class Purchased(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    product = models.ForeignKey(ThriftRegister, on_delete=models.CASCADE)  # 購入した商品
    purchase_date = models.DateTimeField(auto_now_add=True)  # 購入日

    def __str__(self):
        return f"{self.user.username} bought {self.product.title} on {self.purchase_date}"

Django4/thriftproject/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model =CustomUser
        fields = ('username', 'email', 'password1', 'password2')

Django4/thriftproject/accounts/views.py
from django.shortcuts import render
from django.views.generic import CreateView,TemplateView
from .forms import CustomUserCreationForm
from django.urls import reverse_lazy

# Create your views here.
class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    template_name = 'signup.html'
    success_url = reverse_lazy('accounts:signup_success')

    def form_valid(self,form):
        user = form.save()
        self.object = user
        return super().form_valid(form)
    
class SignUpSuccessView(TemplateView):
    template_name = 'signup_success.html'

Django4/thriftproject/thrift/views.py
from django.shortcuts import render,redirect
from django.views.generic import ListView,CreateView,DetailView
from django.urls import reverse_lazy
from .models import ThriftRegister,Purchased
from django.core.mail import send_mail
from django.conf import settings
from django.contrib import messages
# Create your views here.
class IndexView(ListView):
    template_name = 'index.html'
    context_object_name = 'thrifts'
    paginate_by = 6

    def get_queryset(self):
        sort_by = self.request.GET.get('sort_by','posted_at')

        order = self.request.GET.get('order','asc')

        if order == 'desc':
            sort_by = f'-{sort_by}'


        return ThriftRegister.objects.all().order_by(sort_by)

class ProductDetail(DetailView):
    template_name = 'detail.html'

    model = ThriftRegister

    def post(self,request,*args, **kwargs):
        product = self.get_object()

        user_email = request.user.email
        
        if user_email:
            send_mail(
                subject=f'商品購入のお知らせ：{product.title}',
                message=f'{product.title}を購入いただきありがとうございます！',
                from_email=settings.DEFAULT_FROM_EMAIL,
                recipient_list=[user_email],
            )

        purchased = Purchased.objects.create(
            user=request.user,
            product=product,
        )
        
        product.is_purchased = True
        product.save()

        return render(request, 'purchase_success.html',{'product':product})
    
class CategoryView(ListView):
    '''カテゴリページのビュー
    
    Attributes:
      template_name: レンダリングするテンプレート
      paginate_by: 1ページに表示するレコードの件数
    '''
    # index.htmlをレンダリングする
    template_name ='index.html'
    # 1ページに表示するレコードの件数
    paginate_by = 3

    def get_queryset(self):
      '''クエリを実行する
      
      self.kwargsの取得が必要なため、クラス変数querysetではなく、
      get_queryset（）のオーバーライドによりクエリを実行する
      
      Returns:
        クエリによって取得されたレコード
      '''     
      # self.kwargsでキーワードの辞書を取得し、
      # categoryキーの値(Categorysテーブルのid)を取得
      category_id = self.kwargs['category']
      # filter(フィールド名=id)で絞り込む
      categories = ThriftRegister.objects.filter(
        category=category_id).order_by('-posted_at')
      # クエリによって取得されたレコードを返す
      return categories
    
def user_orders(request):
    orders = Purchased.objects.filter(user=request.user).order_by('-purchase_date')
    return render(request, 'mypage.html',{'orders':orders})

Django4/thriftproject/accounts/templates/logout.html
{% extends 'base.html' %}

{% block title %}Log out{% endblock %}

    {% block contents %}

    <div class="container">
        <div class="row">
            <div class="col offset-4 py-4">
                <h3>ログアウトしました</h3>
                <p><a href="{% url 'thrift:index' %}">トップページへ</a></p>
            </div>
        </div>
    </div>
    {% endblock %}

Django4/thriftproject/accounts/templates/password_reset.html
{% extends 'base.html' %}

{% block title %}Reset password{% endblock %}

    {% block contents %}
    <div class="container">
        <div class="row">
            <div class="col py-4">
                <hr>
                <h3>パスワードをリセットしますか？</h3>
                <p>登録済みのメールアドレスを入力してください。パスワードリセットのリンクを記載したメールをすぐにお届けします。</p>
                <br>

                <form action="" method="POST" class="text-center">
                    {% csrf_token %}
                    {{ form }}
                    <input type="submit" value="メールを受け取る" /><br>
                </form>
                <br>
                <a href="{% url 'thrift:index' %}">Thrift shop</a>
                <br>
            </div>
        </div>
    </div>
    {% endblock %}

Django4/thriftproject/accounts/templates/password_reset_done.html
<!doctype html>
<html lang="ja">
    <head>
        <style>
            .pad{
                background-color: lavender;
                border: solid 2px;
                padding-top: 30px;
                padding-bottom: 50px;
                padding-left: 100px;
                margin-top: 50px;
                margin-right: 70px;
                margin-left: 70px;
            }
        </style>
    </head>

    <body>
        <div class="pad">
            <h2>パスワードがリセットされました。</h2>
            <p>
                Tour Password has been set. You may go ahead and login
            </p>
            <br>
            <a href="{% url 'thrift:index' %}">Thrift shopのトップページへ</a>
        </div>
    </body>
</html>

Django4/thriftproject/accounts/templates/password_reset_sent.html
{% extends 'base.html' %}

{% block title %}Send password reset{% endblock %}

    {% block contents %}
    <hr>
    <div class="row">
        <div class="col offset-2 py-4">
            <h5>パスワードのリセット手順をメールで送信しました。メールはすぐに届きます。</h5>
            <br>
            <h6>メールが届かない場合は、登録済みのメールアドレスであるかを確認し、送信メールフォルダも確認してみてください。</h6>
            <br>
            <a href="{% url 'thrift:index' %}">Thrift shop</a>
        </div>
    </div>
    {% endblock %}

Django4/thriftproject/accounts/templates/signup.html
{% extends 'base.html' %}

{% block title %}Sign Up{% endblock %}

        {% block contents %}
        <hr>
        <div class="container">
            <div class="row">
                <div class="col offset-2">
                    <h3>サインアップ</h3>
                    <form method = "post">
                        {% csrf_token %}
                        {% for field in form %}
                            <p>
                                {{ field.label_tag }}<br>
                                {{ field }}
                                {% if field.help_text %}
                                    <small style="color: grey">{{ field.help_text }}</small>
                                {% endif %}
                                {% for error in field.errors %}
                                    <p style="color: red">{{ error }}</p>
                                {% endfor %}
                            </p>
                        {% endfor %}
                        <p style="color:red">
                            ※メールアドレスはパスワードをリセットする際に必要になりますので、登録をお願いします。
                        </p>
                        <input type="submit" value="Sign up">
                    </form>
                    <br>
                    <p><a href="{% url 'thrift:index' %}">登録をやめてトップページに戻る</a></p>
                </div>
            </div>
        </div>
        {% endblock %}

Django4/thriftproject/accounts/templates/signup_success.html
{% extends 'base.html' %}
{% block title %}Registraction Complete{% endblock %}

        {% block contents %}
        <div class="container">
            <div class="row">
                <div class="col offset-4 py-4">
                    <h3>登録が完了しました</h3>
                    <p><a href="{% url 'accounts:login' %}">ログインはこちら</a></p>
                </div>
            </div>
        </div>
        {% endblock %}

Django4/thriftproject/thrift/templates/base.html
{% load static %}
<!doctype html>
<html lang="ja">
  <head><script src="../assets/js/color-modes.js"></script>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.112.5">
    <title>{% block title %}{% endblock %}</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        width: 100%;
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }

      .btn-bd-primary {
        --bd-violet-bg: #712cf9;
        --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

        --bs-btn-font-weight: 600;
        --bs-btn-color: var(--bs-white);
        --bs-btn-bg: var(--bd-violet-bg);
        --bs-btn-border-color: var(--bd-violet-bg);
        --bs-btn-hover-color: var(--bs-white);
        --bs-btn-hover-bg: #6528e0;
        --bs-btn-hover-border-color: #6528e0;
        --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
        --bs-btn-active-color: var(--bs-btn-hover-color);
        --bs-btn-active-bg: #5a23c8;
        --bs-btn-active-border-color: #5a23c8;
      }
      .bd-mode-toggle {
        z-index: 1500;
      }
    </style>

    
  </head>
  <body>
    <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
      <symbol id="check2" viewBox="0 0 16 16">
        <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
      </symbol>
      <symbol id="circle-half" viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"/>
      </symbol>
      <symbol id="moon-stars-fill" viewBox="0 0 16 16">
        <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"/>
        <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"/>
      </symbol>
      <symbol id="sun-fill" viewBox="0 0 16 16">
        <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
      </symbol>
    </svg>

    <div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
      <button class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center"
              id="bd-theme"
              type="button"
              aria-expanded="false"
              data-bs-toggle="dropdown"
              aria-label="Toggle theme (auto)">
        <svg class="bi my-1 theme-icon-active" width="1em" height="1em"><use href="#circle-half"></use></svg>
        <span class="visually-hidden" id="bd-theme-text">Toggle theme</span>
      </button>
      <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light" aria-pressed="false">
            <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em"><use href="#sun-fill"></use></svg>
            Light
            <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
          </button>
        </li>
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="dark" aria-pressed="false">
            <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em"><use href="#moon-stars-fill"></use></svg>
            Dark
            <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
          </button>
        </li>
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="auto" aria-pressed="true">
            <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em"><use href="#circle-half"></use></svg>
            Auto
            <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
          </button>
        </li>
      </ul>
    </div>

    
<header data-bs-theme="dark">
  <div class="collapse text-bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4>thrift shop</h4>
          <p class="text-body-secondary">enjoy shopping!</p>
          <ul class="list-unstyled">
            <li><a href="{% url 'thrift:thrifts_cat' category=1 %}" class="text-white">トップス</a></li>
            <li><a href="{% url 'thrift:thrifts_cat' category=2 %}" class="text-white">ボトムス</a></li>
            <li><a href="{% url 'thrift:thrifts_cat' category=3 %}" class="text-white">アウター</a></li>
            <li><a href="{% url 'thrift:thrifts_cat' category=4 %}" class="text-white">その他</a></li>
          </ul>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4>Contact</h4>
          <ul class="list-unstyled">
            {% if user.is_authenticated %}
            <li><a href='{% url "thrift:mypage" %}' class="text-white">マイページ</a></li>
            <li><a href="{% url 'accounts:logout' %}" class="text-white">ログアウト</a></li>
            <li><a href="{% url 'password_reset' %}"></a></li>
            <li><a href="#" class="text-white">Email me</a></li>
            {% else %}
            <li><a href="{% url 'accounts:signup' %}" class="text-white">サインアップ</a></li>
            <li><a href="{% url 'accounts:login' %}" class="text-white">ログイン</a></li>
            {% endif %}
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container">
      <a href="{% url 'thrift:index' %}" class="navbar-brand d-flex align-items-center">
        <img src="{% static 'img/thrift_ico.png' %}" width="30" height="30" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2" viewBox="0 0 24 24"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/><circle cx="12" cy="13" r="4"/></img>
        <strong style="font-size:28px;">thrift shop</strong>
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>
</header>

<main>
{% block contents %}{% endblock %}
</main>

<footer class="text-body-secondary py-5">
  <div class="container">
    <p class="float-end mb-1">
      <a href="{% url 'thrift:index' %}">Back to top</a>
    </p>
    <p class="mb-1">Thrift shop is &copy; Bootstrap, but please download and customize it for yourself!</p>
  </div>
</footer>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    </body>
</html>

Django4/thriftproject/thrift/templates/index.html
{% extends 'base.html' %}
{% block title %}Thrift Shop{% endblock %}

    {% block contents %}

    {% include 'thrift_title.html' %}
    {% include 'thrift_list.html' %}

    {% include 'pagination.html' %}
    
    {% endblock %}

Django4/thriftproject/thrift/templates/mypage.html
{% extends 'base.html' %}

{% block title %}MyPage{% endblock %}

{% block contents %}

<div class="container">
        <br>
        <h2>購入した商品</h2>
        <hr>
        {% if orders %}
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols- g-3">
            {% for record in orders %}
            <div class="col">
                <div class="card shadow-sm">
                    <a href='{% url "thrift:product_detail" record.product.pk %}'><img src="{{ record.product.image1.url }}" class="bd-placeholder-img card-img-top" width="75%" height="75%" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title></title><rect width="100%" height="100%" fill="#55595c"/></a>
                    <div class="card-body">
                        <h5 class="card-title">{{ record.product.title }}</h5>
                        <p class="card-text" style="font-size:large; font-weight:bold; color:red;">￥{{ record.product.price }}円</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <small class="text-body-secondary">{{ record.purchase_date }}に購入</small>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        {% else %}
        <p style="text-align:center;">購入履歴がありません</p>
        {% endif %}
</div>
{% endblock %}

Django4/thriftproject/thrift/templates/purchase_success.html
{% extends 'base.html' %}

{% block title %}Purchased{% endblock %}

{% block contents %}
<div class="container">
    <div class="row">
        <div class="col offset-3 py-4">
            <h3>ご購入ありがとうございます！</h3>
            <p><a href="{% url 'thrift:index' %}">トップページへ</a></p>
        </div>
    </div>
</div>
{% endblock %}

Django4/thriftproject/thrift/templates/thrift_title.html
{% load static %}

<style>
  .slide{
    animation: SlideIn 1.6s;
  }

  @keyframes SlideIn {
  0% {
    opacity: 0;
    transform: translateY(-64px);
  }
  100% {
    opacity: 1;
    transform: translateY(0);
  }
}
</style>

<div style="background-size:cover; background-image:url({% static 'img/backtitle.jpg' %}); ">
<section class="py-5 text-center container slide">
    <div class="row py-lg-5">
      <div class="co-lg-6 col-md-8 mx-auto">
        <h1 style="color:rgb(207, 167, 167); -webkit-text-stroke-width:1px; -webkit-text-stroke-color: white;" class="fw-light">Thtift shop</h1>
        <p class="lead text-body-secondary" style="-webkit-text-stroke-width:1px; -webkit-text-stroke-color:white;">let's enjoy shopping!</p>
        <p>
          {% if user.is_authenticated %}
          <a href="{% url 'thrift:mypage' %}" class="btn btn-primary my-2">マイページ</a>
          <a href="{% url 'accounts:logout' %}" class="btn btn-secondary my-2">ログアウト</a>
          {% else %}
          <a href="{% url 'accounts:signup' %}" class="btn btn-primary my-2">サインアップ</a>
          <a href="{% url 'accounts:login' %}" class="btn btn-secondary my-2">ログイン</a>
          {% endif %}
        </p>
      </div>
    </div>
  </section>
</div>